### ISSUE TITLE
errors in generating .pkl

### ISSUE THREAD

**Issue by clorislili** [nickgkan/beauty_detr#3]
Hi, I try to generate the .pkl of all scans, but it always resulted in the error of multi processing after loading all scans. Are you available to upload a train.pkl and val.pkl?

**Comment by nickgkan** [comment]
Hi,
These files are big and depend on relative code structure, so we cannot upload them.
You should be able to generate them though if you follow the instructions in the README.

If you encounter a problem while following those instructions, please let us know the details, so that we can best help you.
Good luck!

**Comment by clorislili** [comment]
Solved! Thank you so much and appreciate your work a lot :)
